name: database_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  injectable: ^2.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.8
  flutter_gen_runner: any
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
